# Generated by Django 3.2.8 on 2021-11-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211105_2138'),
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.DateTimeField(verbose_name='Время сеанса'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Название фильма'),
        ),
    ]
