# Generated by Django 3.2.8 on 2021-11-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_name'),
        ('actors', '0002_auto_20211105_2138'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=404, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default='ERROR, PLS PUT GENRE', on_delete=django.db.models.deletion.SET_DEFAULT, to='genres.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_actor',
            field=models.ForeignKey(default='ERROR, PLS PUT ACTOR', on_delete=django.db.models.deletion.SET_DEFAULT, to='actors.actor', verbose_name='Главный актер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
