# Generated by Django 3.2.8 on 2021-11-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('year', models.IntegerField(default=404, verbose_name='Год')),
                ('link', models.CharField(max_length=64, verbose_name='Ссылка на трейлер')),
                ('img', models.CharField(max_length=64, verbose_name='Ссылка на static img')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('genre', models.ForeignKey(default='ERROR, PLS PUT GENRE', on_delete=django.db.models.deletion.SET_DEFAULT, to='genres.genre', verbose_name='Жанр')),
                ('main_actor', models.ForeignKey(default='ERROR, PLS PUT ACTOR', on_delete=django.db.models.deletion.SET_DEFAULT, to='actors.actor', verbose_name='Главный актер')),
            ],
        ),
    ]
