# Generated by Django 3.2.8 on 2021-11-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='movie',
        ),
    ]
